#!/bin/bash

if [[ $CI != true ]]; then
    cat << EOF > src/aws-exports2.js
    /* eslint-disable */
    // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

    const awsmobile = {
        aws_project_region: '${AWS_DEFAULT_REGION}',
        aws_cognito_identity_pool_id: '${LOCAL_IDENTITY_POOL_ID}',
        aws_cognito_region: '${AWS_DEFAULT_REGION}',
        aws_user_pools_id: '${LOCAL_USER_POOL_ID}',
        aws_user_pools_web_client_id: '${LOCAL_WEB_CLIENT_ID}',
        oauth: {
            domain: '${LOCAL_OAUTH_DOMAIN}',
            scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:8000',
            redirectSignOut: 'http://localhost:8000',
            responseType: 'code',
        },
        federationTarget: 'COGNITO_USER_POOLS',
        aws_cognito_username_attributes: ['EMAIL'],
        aws_cognito_social_providers: ['GOOGLE', 'FACEBOOK', 'AMAZON'],
        aws_cognito_signup_attributes: ['EMAIL', 'NAME', 'PICTURE'],
        aws_cognito_mfa_configuration: 'OPTIONAL',
        aws_cognito_mfa_types: ['TOTP'],
        aws_cognito_password_protection_settings: {
            passwordPolicyMinLength: 8,
            passwordPolicyCharacters: [
                "REQUIRES_LOWERCASE",
                "REQUIRES_NUMBERS",
                "REQUIRES_SYMBOLS",
                "REQUIRES_UPPERCASE"
            ],
        },
        aws_cognito_verification_mechanisms: ['EMAIL'],
    };

    export default awsmobile;
EOF
fi